### ISSUE TITLE
Undefined $firstName and $lastName variables in submitForm($formId, $address)

### ISSUE THREAD

**Issue by jaltek** [newsletter2go/newsletter2go-api-php#15]
Hi,
the `$firstName` and `$lastName` variables inside the `submitForm($formId, $address)` function are undefined and it is not possible to fill them.

https://github.com/newsletter2go/newsletter2go-api-php/blob/a82ea04b01f65752c8536bb0fc45cae34f59dee1/src/Newsletter2Go_REST_Api.php#L840-L855

**Comment by jaltek** [comment]
Second: The `$data` variable is also undefined. So the result is not returned:

https://github.com/newsletter2go/newsletter2go-api-php/blob/a82ea04b01f65752c8536bb0fc45cae34f59dee1/src/Newsletter2Go_REST_Api.php#L859

**Comment by hirbod** [comment]
That API is a joke. There is also a var_dump at the end of _curl. The README has more data then the actual released version of composer. I mean guys, r u joking around?

**Comment by mfrenzel** [comment]
@jaltek thanks for your input we fixed that in the last release by removing the method because the endpoint can be used by calling addRecipientViaForm (https://github.com/newsletter2go/newsletter2go-api-php/issues/18)

@Hirbod obviously the last PR was not reviewed very good. We fixed the most annoying issues. Feel free to create another issue here if you notice some other problems.
