### ISSUE TITLE
Wrong Request Method in UpdateRecipient and UpdateRecipients

### ISSUE THREAD

**Issue by Gw4rn** [newsletter2go/newsletter2go-api-php#16]
According to your API Docs for UpdateRecipient() and UpdateRecipients() the request method should not be static::POSTbut static::PATCH. Otherwise you will get an "method not allowed" error message. Could you please fix that?

UpdateRecipients
https://github.com/newsletter2go/newsletter2go-api-php/blob/a82ea04b01f65752c8536bb0fc45cae34f59dee1/src/Newsletter2Go_REST_Api.php#L300

API Doc UpdateRecipients
https://docs.newsletter2go.com/?version=latest#b16f71d0-0d63-4df0-a750-7dc4e8515bcc

UpdateRecipient
https://github.com/newsletter2go/newsletter2go-api-php/blob/a82ea04b01f65752c8536bb0fc45cae34f59dee1/src/Newsletter2Go_REST_Api.php#L332

API Doc UpdateRecipient
https://docs.newsletter2go.com/?version=latest#6f4acfc5-649a-4345-9456-6cad24fa9fee

**Comment by mfrenzel** [comment]
@Gw4rn thanks for your input. Actually the endpoints are working as POST requests because the endpoint will update already existing recipients automatically.
But while investigating we figured out that one of the endpoints were wrongly called indeed. This is fixed [here](https://github.com/newsletter2go/newsletter2go-api-php/blob/master/src/Newsletter2Go_REST_Api.php#L303)
